org: asasigure
app: aws-wotagei-ranking-project
service: wotagei-ranking

frameworkVersion: "3"

useDotenv: true

custom:
  tableName: "wotagei-ranking-${sls:stage}"

provider:
  name: aws
  region: ap-northeast-1
  runtime: nodejs14.x
  iam:
    role:
      statements:
        - Effect: Allow
          Action:
            - dynamodb:Query
            - dynamodb:Scan
            - dynamodb:GetItem
            - dynamodb:PutItem
            - dynamodb:UpdateItem
            - dynamodb:DeleteItem
          Resource:
            - Fn::GetAtt: [UsersTable, Arn]

functions:
  hello:
    handler: handler.hello
    environment:
      YOUTUBE_DATA_API_KEY: ${env:YOUTUBE_DATA_API_KEY}
      TABLE_NAME: ${self:custom.tableName}

resources:
  Resources:
    UsersTable:
      Type: AWS::DynamoDB::Table
      Properties:
        AttributeDefinitions:
          - AttributeName: week
            AttributeType: N
          - AttributeName: views
            AttributeType: N
        KeySchema:
          - AttributeName: week
            KeyType: HASH
          - AttributeName: views
            KeyType: RANGE
        BillingMode: PAY_PER_REQUEST
        TableName: ${self:custom.tableName}

plugins:
  - serverless-bundle
